PROJECT=adpadvertiser
PROJECT_NAME=adpadvertiser
PROJECT_VERSION?=20140113
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=BSD
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://github.com/jdkoftinoff/adpadvertiser
PROJECT_IDENTIFIER=com.statusbar.adpadvertiser
TOP_LIB_DIRS+=. 
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

JDKSAVDECC_C_DIR?=../jdksavdecc-c
MICROSUPPORT_DIR?=../microsupport

TOP_LIB_DIRS+=$(MICROSUPPORT_DIR) $(JDKSAVDECC_C_DIR)

CONFIG_TOOLS=

COMPILE_FLAGS+=-Wall -W

#STRIP?=true

ifdef US_ENABLE_RAW_ETHERNET
DEFINES+=US_ENABLE_RAW_ETHERNET=$(US_ENABLE_RAW_ETHERNET)
endif

ifdef US_ENABLE_PCAP
DEFINES+=US_ENABLE_RAW_ETHERNET=1
DEFINES+=US_ENABLE_PCAP=$(US_ENABLE_PCAP)
LDLIBS+=-lpcap
endif


